# USB RNDIS DHCP pool for host computer
interface=usb0
dhcp-range=192.168.68.2,192.168.68.99,255.255.255.0,12h
dhcp-option=option:router,192.168.68.1
dhcp-option=option:dns-server,223.5.5.5,8.8.8.8
no-resolv
no-poll
