# debian-ufi001b build configuration
DISTRO=bookworm
ARCH=arm64

# Kernel (pmOS mainline for MSM8916)
KERNEL_REPO=https://github.com/pmos-on-uefi/uefi-builds
KERNEL_APK=linux-kernel-mainline-6.6.0-msm8916.apk
